server:
  port: 8083
spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/proselytes3
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/proselytes3
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
